apiVersion: v1
kind: Service
metadata:
  name: astana-price-api
  labels:
    app: astana-price-api
spec:
  type: LoadBalancer
  selector:
    app: astana-price-api
  ports:
  - port: 80
    targetPort: 9696
    protocol: TCP
    name: http